# Configuration for the file encoding converter

# 要转换的文件或目录的路径。
path = "."

# 当'path'是目录时要处理的文件扩展名。
file_extension = "txt"

# 文件要转换成的目标编码。
output_encoding = "utf-8"

# 如果自动检测失败，可以尝试的输入编码列表。
# 程序将按给定顺序尝试它们。
input_encodings = ["gb2312", "gbk", "gb18030", "big5"]