# Configuration for the file encoding converter

# The path to the file or directory to convert.
# Can be an absolute path (e.g., "C:\\Users\\Admin\\Documents")
# or a relative path from where the program is run (e.g., "data_files").
path = "."

# The target encoding to convert files to.
# Common values: "utf-8", "utf-16le", "utf-16be", "latin1"
target_encoding = "utf-8"

# The file extension to process when 'path' is a directory.
# The converter will only affect files with this extension.
file_extension = "txt"
