[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["config.toml"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-pc-windows-msvc"]
# The installers to generate for each app
installers = []
